package reporting;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Abstract base class for all report generators.
 * Provides common structure, fields, and methods for report generation.
 */
public abstract class ReportGenerator {
    
    protected String reportTitle;
    protected LocalDateTime reportDate;
    protected String generatedBy;
    protected LocalDate startDate;
    protected LocalDate endDate;
    protected List<String> categoryFilters;
    
    protected static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    protected static final DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    protected static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("HH:mm:ss");
    
    public ReportGenerator(String reportTitle, String generatedBy) {
        this.reportTitle = reportTitle;
        this.reportDate = LocalDateTime.now();
        this.generatedBy = generatedBy;
        this.categoryFilters = new ArrayList<>();
    }
    
    /**
     * Generate the report with formatted data
     */
    public abstract Object generateReport();
    
    /**
     * Get raw report data for export
     */
    public abstract Map<String, Object> getReportData();
    
    /**
     * Set the date range for report filtering
     */
    public void setDateRange(LocalDate startDate, LocalDate endDate) {
        this.startDate = startDate;
        this.endDate = endDate;
    }
    
    /**
     * Add category filter
     */
    public void addCategoryFilter(String category) {
        this.categoryFilters.add(category);
    }
    
    /**
     * Clear all category filters
     */
    public void clearCategoryFilters() {
        this.categoryFilters.clear();
    }
    
    /**
     * Format currency value
     */
    protected String formatCurrency(double amount) {
        return String.format("₹%.2f", amount);
    }
    
    /**
     * Format percentage value
     */
    protected String formatPercentage(double percentage) {
        return String.format("%.2f%%", percentage);
    }
    
    /**
     * Format date
     */
    protected String formatDate(LocalDate date) {
        return date != null ? date.format(DATE_FORMATTER) : "";
    }
    
    /**
     * Format date-time
     */
    protected String formatDateTime(LocalDateTime dateTime) {
        return dateTime != null ? dateTime.format(DATETIME_FORMATTER) : "";
    }
    
    /**
     * Get report header with common information
     */
    protected String getReportHeader() {
        StringBuilder header = new StringBuilder();
        header.append("=".repeat(80)).append("\n");
        header.append(String.format("%s%n", reportTitle));
        header.append("-".repeat(80)).append("\n");
        header.append(String.format("Generated on: %s%n", formatDateTime(reportDate)));
        header.append(String.format("Generated by: %s%n", generatedBy));
        
        if (startDate != null && endDate != null) {
            header.append(String.format("Period: %s to %s%n", formatDate(startDate), formatDate(endDate)));
        }
        
        if (!categoryFilters.isEmpty()) {
            header.append(String.format("Categories: %s%n", String.join(", ", categoryFilters)));
        }
        
        header.append("=".repeat(80)).append("\n");
        return header.toString();
    }
    
    /**
     * Get report footer
     */
    protected String getReportFooter() {
        return "-".repeat(80) + "\n" +
               "End of Report\n" +
               "=".repeat(80);
    }
    
    /**
     * Calculate percentage
     */
    protected double calculatePercentage(double value, double total) {
        return total > 0 ? (value / total) * 100 : 0;
    }
    
    /**
     * Round to 2 decimal places
     */
    protected double roundToTwoDecimals(double value) {
        return Math.round(value * 100.0) / 100.0;
    }
    
    /**
     * Get report title
     */
    public String getReportTitle() {
        return reportTitle;
    }
    
    /**
     * Get report generation date
     */
    public LocalDateTime getReportDate() {
        return reportDate;
    }
    
    /**
     * Get user who generated the report
     */
    public String getGeneratedBy() {
        return generatedBy;
    }
}
